name: My Python Demo

on: 
  push:
  schedule:
    # 11th minute of the 1st hour on a Monday
    - cron: '11 0 * * 1'

permissions: write-all

jobs:
  name-of-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: pip install requests
      - run: python script.py
          

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "actions commit"
          git merge
          git push
